### ISSUE TITLE
saving PFT files from Database definitions menu problem

### ISSUE THREAD

**Issue by edsz14** [ABCD-DEVCOM/ABCD2#3]
The 'function enviar()' at line 85 of the script dbadmin/leer_txt.php : 
       window.opener.document.forma1.pft.value=esc(document.forma1.pftedit.value)
no longer seems to work correctly in both Windows and Linux.
This prevents edited PFT's from being saved ('sent') to the file-system.

**Comment by fho4abcd** [comment]
This script is modified, exactly on the suspected line 85 in commit "Central update to 2.2 and adding OPAC".
A check revealed that the code functions now on Linux and Windows, so this request can be closed.
