### ISSUE TITLE
MX 

### ISSUE THREAD

**Issue by aldoeri** [ABCD-DEVCOM/ABCD2#316]
mx is giving me trobules I have windows 10 64bits 
![64 bits](https://user-images.githubusercontent.com/25265688/155646490-cae8276e-8876-4058-a4e6-70922c2279b6.jpg)
so what can i do im using defender and it need to work in 64 bit not in 32

**Comment by fho4abcd** [comment]
The executables for ABCD 2.2 in git are all compiled for 64 bits.
May be you have to reload from from git if you do not trust the 32/64 bit your actual used executable.
The standard (e.g. 16-60) utf-8 can be tested by mx what. Output
 ./mx.exe what
CISISUNI Interface v6.0a/PC32/W/M/32767/16/60/I/UTF-8:Jun  2 2016 - Utility MX
CISISUNI Interface v6.0a/.iy0/Z/GIZ/DEC/ISI/UTL/INVX/B7/FAT/CIP/CGI/MX/W
Copyright (c)BIREME/PAHO/EdS 2015. [http://wiki.bireme.org/en/index.php/CISIS]

The message above stems from windows defender or other firewall related program in windows.
This is not the area on which we can advise you

**Comment by fho4abcd** [comment]
Addition: The programs are 32 bits but run on 64 bit platformas
