### ISSUE TITLE
winisis is not working for a new database 

### ISSUE THREAD

**Issue by aldoeri** [ABCD-DEVCOM/ABCD2#344]
i hope you  check it

**Comment by edsz14** [comment]
A few comments : 
- this area is not about WinISIS - which by the way is a 'dead' software no longer being developed or supported
- based on the information you give nobody can do anything about it; just stating 'it' is not working does not allow to check 'it'...


     On Thursday, March 17, 2022, 03:53:03 AM GMT+1, aldoeri ***@***.***> wrote:  
 
 


i hope you check it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fho4abcd** [comment]
Issues without any context and/or  without detailed problem description cannot be answered and will be closed. It is impossible to guess what the software environment is. (e.g OS, web infrastructure,  ABCD version, location and configuration). It is impossible to guess how the problem is found.

**Comment by aldoeri** [comment]
i was refering in ABCD when you do a new database in the last version of ABCD

**Comment by fho4train** [comment]
OK, thanks
    As eds already indicated. Winisis is dead.
    The existence of the option is an error. It will be removed in the
    upcoming release
    
    Op 2022-03-17 om 12:53 schreef aldoeri:
    
    
      
      i was refering in ABCD when you do a new database in
        the last version of ABCD
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/ABCD-DEVCOM/ABCD2/issues/344#issuecomment-1070833144",
"url": "https://github.com/ABCD-DEVCOM/ABCD2/issues/344#issuecomment-1070833144",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by aldoeri** [comment]
![fdt](https://user-images.githubusercontent.com/25265688/158935661-d2e6ce2e-4426-403b-9b5a-a9c95327aaf1.jpg)
