### ISSUE TITLE
document root 

### ISSUE THREAD

**Issue by aldoeri** [ABCD-DEVCOM/ABCD2#401]
where is the document root in wamp ? because i cant see it

**Comment by rogercgui** [comment]
Hello,
This repository is about ABCD, but about your question I found on StackOverflow the information that the root of WAMP is c:\wamp\www

Source: https://stackoverflow.com/questions/6233572/where-is-the-web-server-root-directory-in-wamp

**Comment by aldoeri** [comment]
No tengo la fortuna de ser programador como usted soy solo bibliotecario y
de una u otra manera WAMP convive con ABCD desgraciadamente siempre he
tenidoi problemas al configurar porque se mezcla en el manual Linux con
Windows y para colmo de males no siempre son claros  ni aun en los
ejemplos   por eso hace más de 1 año pedí q se separará Windows de Linux g
si usted lee los mensajes enviados al foro de CDS/ISIS se dará cuenta  yo
vengo desde la época en q CDS/Isis estaba en Pascal nunca había tenido
tantos problemas con Isis hasta ahora
